config/routes.rb
Writeriki::Application.routes.draw do

  get "propart/index"

  resources :messages do
    member do
      get :reply
    end
  end

  match '/inbox' => 'messages#inbox', :as => 'inbox'
  match '/outbox' => 'messages#outbox', :as => 'outbox'
  match '/trash' => 'messages#trash', :as => 'trash'
  match '/trash/restore' => 'messages#restore', :as => 'restore'
  match '/messages/:id/reply' => 'messages#reply'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users

  resources :activities

  resources :attachments
  
  resources :discusses do
    resources :comments
  end

  resources :events do
    resources :comments
    member do
      get :asc
    end
  end
  
  resources :docs do
    resources :comments
  end

  resources :projects do
    member do
      get :join,:quit
    end
  end

  match '/myprojects' => 'myprojects#index', :as => 'myproject'

  match '/mydocs' => 'mydocs#index', :as => 'mydoc'

  match '/myevents' => 'myevents#index', :as =>'myevent'

  match '/tasks' => 'task#index', :as => 'task'

  match '/joins' => 'propart#index', :as => 'joins'

  root :to => 'projects#index'

end

app/models/message.rb
class Message < ActsAsMessageable::Message
  attr_accessible :title, :body
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :authenticate_user!

  # GET /messages
  # GET /messages.json
  def index
    @messages = current_user.received_messages

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = current_user.messages.find(params[:id])
    @message.mark_as_unread
  end

  def reply
    @message = current_user.messages.find(params[:id])
    @message.reply(params[:topic], params[:body])
    redirect_to inbox_url
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # POST /messages
  # POST /messages.json
  def create
      @to = User.find(params[:message][:to])
      current_user.send_message(@to, params[:message][:topic], params[:message][:body])
      redirect_to outbox_url
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    #@message = Message.find(params[:id])
    #@message.destroy
    #redirect_to projects_path
    current_user.delete_message(ActsAsMessageable::Message.find(params[:id]))
    redirect_to trash_url
  end

  def outbox
    @messages = current_user.sent_messages
  end

  def inbox
    @messages = current_user.received_messages
  end

  def trash
    @messages = current_user.deleted_messages
  end

  def restore
    current_user.deleted_messages.process do |m|
      m.restore # @alice restore 'm' message from trash
    end
    redirect_to inbox_url
  end

end

app/views/messages/_form.html.erb
<%= form_for @message,:html => { :class => 'form-horizontal' } do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% user_array = User.all.map { |user| [user.username,user.id]} %>

    <div class="control-group">
      <%= f.label :to, class:"control-label" %>
      <div class="controls">
        <%= f.select :to, options_for_select(user_array),{},:id => 'e1',class:'span4' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :topic, class:'control-label' %>
      <div class="controls">
        <%= f.text_field :topic, class:'span4' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :body, class:'control-label' %>
      <div class="controls">
        <%= f.text_field :body,class:'span4' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.submit "submit", class:'btn btn-info btn-large' %>
    </div>
<% end %>

<!--选择收信人使用select2样式-->
<script>
    $(document).ready(function() {
        $("#e1").select2();
    });
</script>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/inbox.html.erb
<% provide(:title, '收信箱') %>

<h4 class="title-border-left">
  收信箱
</h4>

<%= render :partial => 'snippet/panel' %>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <th>topic</th>
    <th>body</th>
    <th></th>
    <th></th>
  </tr>

  <% @messages.each do |message| %>
      <tr>
        <td><%= message.id %></td>
        <td><%= link_to message.topic, message %></td>
        <td><%= message.body %></td>
        <td><%= link_to '查看', message %></td>
        <td><%= link_to '删除', message,:method => :delete %></td>
      </tr>
  <% end %>
</table>

app/views/messages/index.html.erb
<% provide(:title, '站内信') %>

<h4 class="title-border-left">
  站内信操作
</h4>

<%= render :partial => 'snippet/panel' %>

app/views/messages/new.html.erb
<% provide(:title, '写消息') %>

<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/outbox.html.erb
<% provide(:title, '发信箱') %>

<h4 class="title-border-left">
  发信箱
</h4>

<%= render :partial => 'snippet/panel' %>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <th>topic</th>
    <th>body</th>
    <th></th>
    <th></th>
  </tr>

  <% @messages.each do |message| %>
      <tr>
        <td><%= message.id %></td>
        <td><%= link_to message.topic, message %></td>
        <td><%= message.body %></td>
        <td><%= link_to '查看', message %></td>
        <td><%= link_to '删除', message,:method => :delete %></td>
      </tr>
  <% end %>
</table>

app/views/messages/show.html.erb
<% provide(:title, @message.topic) %>

<h4 class="title-border-left">
  站内信操作
</h4>

<%= render :partial => 'snippet/panel' %>

<%= @message.id %>
<%= @message.topic %>
<%= @message.body %>

<hr>

<% @hello = @message.conversation %>
<% @hello.each do |a| %>
    <%= a.id %>
<% end %>

<%= link_to 'Back', inbox_path %>

<%= form_tag(:action => 'reply') do %>
    <div class="control-group">
      <%= label_tag(:topic, "Topic:") %>
      <div class="controls">
        <%= text_field_tag(:topic) %>
      </div>
    </div>
    <div class="control-group">
      <%= label_tag(:body, "Body:") %>
      <div class="controls">
        <%= text_field_tag(:body) %>
      </div>
    </div>
    <div class="control-group">
      <%= submit_tag("Reply") %>
    </div>
<% end %>

app/views/messages/trash.html.erb
<% provide(:title, '回收站') %>

<h4 class="title-border-left">
  回收站
</h4>

<%= render :partial => 'snippet/panel' %>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <th>topic</th>
    <th>body</th>
    <th></th>
    <th></th>
  </tr>

  <% @messages.each do |message| %>
      <tr>
        <td><%= message.id %></td>
        <td><%= link_to message.topic, message %></td>
        <td><%= message.body %></td>
        <td><%= link_to '永久删除', message,:method => :delete %></td>
        <td><%= link_to '还原', :controller => :messages, :action => :restore %></td>
      </tr>
  <% end %>
</table>