config/routes.rb
Writeriki::Application.routes.draw do

  get "propart/index"

  resources :messages do
    member do
      get :reply
    end
  end

  match '/inbox' => 'messages#inbox', :as => 'inbox'
  match '/outbox' => 'messages#outbox', :as => 'outbox'
  match '/trash' => 'messages#trash', :as => 'trash'
  match '/trash/restore' => 'messages#restore', :as => 'restore'
  match '/messages/:id/reply' => 'messages#reply'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users

  resources :activities

  resources :attachments
  
  resources :discusses do
    resources :comments
  end

  resources :events do
    resources :comments
    member do
      get :asc
    end
  end
  
  resources :docs do
    resources :comments
  end

  resources :projects do
    member do
      get :join,:quit
    end
  end

  match '/myprojects' => 'myprojects#index', :as => 'myproject'

  match '/mydocs' => 'mydocs#index', :as => 'mydoc'

  match '/myevents' => 'myevents#index', :as =>'myevent'

  match '/tasks' => 'task#index', :as => 'task'

  match '/joins' => 'propart#index', :as => 'joins'

  root :to => 'projects#index'

end

app/models/doc.rb
class Doc < ActiveRecord::Base
  include PublicActivity::Model
  tracked :owner => Proc.new{ |controller, model| controller.current_user }

  attr_accessible :content, :keyword, :title, :user_id, :project_id

  belongs_to :user
  belongs_to :project
  has_many :comments, :as => :commentable
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_filter :authenticate_user!
  # GET /docs
  # GET /docs.json
  def index
    @docs = Doc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @docs }
    end
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
    @doc = Doc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doc }
    end
  end

  # GET /docs/new
  # GET /docs/new.json
  def new
    @doc = Doc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doc }
    end
  end

  # GET /docs/1/edit
  def edit
      @doc = Doc.find(params[:id])
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = current_user.docs.new(params[:doc])

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: 'Doc was successfully created.' }
        format.json { render json: @doc, status: :created, location: @doc }
      else
        format.html { render action: "new" }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /docs/1
  # PUT /docs/1.json
  def update
    @doc = Doc.find(params[:id])

    respond_to do |format|
      if @doc.update_attributes(params[:doc])
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    respond_to do |format|
      format.html { redirect_to docs_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_form.html.erb
<%= form_for(@doc) do |f| %>
  <% if @doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% @doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_name %>
    <!--找出用户参加的项目，并填充到project_array数组中-->
     <% @joins = Duty.all %>
     <% project_array = Array.new %>
     <% @joins.each do |j| %>
       <% if j.user_id == current_user.id %>
         <% @join_pro = Project.where("id = ?", j.project_id) %>
         <% @join_pro.each do |join| %>
           <% project_array.push( join.name, join.id) %>
         <% end %>
       <% end %>
     <% end %>
     <!--END-->

     <!--提取用户自己创建的项目-->
     <% @pros = Project.where("user_id = ?", current_user.id) %>
     <% @pros.each do |pro| %>
        <% project_array.push( pro.name, pro.id ) %>
     <% end %>
     <!--END-->

    <% projects_array = Hash[*project_array.flatten] %>
    <%= f.select :project_id, options_for_select(projects_array),{}, :id => 'e1',:class => 'span3' %>
  </div>

    <script>
        $(document).ready(function() { $("#e1").select2(); });
    </script>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, class:'wysihtml5',:style => 'width:570px; height:100px;' %>
  </div>
  <div class="field">
    <%= f.label :keyword %>
    <%= f.text_field :keyword %>
  </div>
  <div class="actions">
    <%= f.submit(:class => 'btn btn-info') %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing doc</h1>

<%= render 'form' %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
  <h3 class="title-border-left">
    All docs
  </h3>

  <button class="btn pull-right" style="margin-top: -46px;margin-right: 90px;">只看组长文档</button>

  <div class="btn-group pull-right" style="margin-top: -46px;">
    <button class="btn">排序</button>
    <button class="btn dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li class="divider"></li>
      <li>
        <a href=""> 只浏览组长的文档</a>
      </li>
      <li>
        <a href="">从最新排序</a>
      </li>
      <li>
        <a href="">从旧时排序</a>
      </li>
      <li class="divider"></li>
    </ul>
  </div>

  <hr>

<table class="table table-bordered table-hover">
  <tr>
    <th class="t-center">创建者</th>
    <th class="t-center">标题</th>
    <th class="t-center">内容梗概</th>
    <th class="t-center">关键词</th>
  </tr>

<% @docs.each do |doc| %>
  <tr>
    <td class="span1"><%= doc.user_id %></td>
    <td class="span3"><%= link_to doc.title, doc %></td>
    <td><%= doc.content %></td>
    <td class="span3"><%= doc.keyword %></td>
  </tr>
<% end %>
</table>

<hr>

<%= link_to 'New Doc', new_doc_path, class:"btn btn-danger" %>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render 'form' %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @doc.title %>
</p>

<p>
  <b>Content:</b>
  <%= @doc.content %>
</p>

<p>
  <b>Keyword:</b>
  <%= @doc.keyword %>
</p>


<%= link_to 'Edit', edit_doc_path(@doc) %> |
<%= link_to 'Back', docs_path %>

<ul id="comments">
  <% @doc.comments.each do |comment| %>
      <li><%= comment.content %></li>
  <% end %>
</ul>

<h2>New Comment</h2>
<%= form_for [@doc, Comment.new] do |f| %>
    <div class="field">
      <%= f.label :content %><br />
      <%= f.text_area :content, :rows => 5 %>
    </div>
    <div class="actions">
      <%= f.submit "Add comment",:class => 'btn' %>
    </div>
<% end %>