config/routes.rb
Writeriki::Application.routes.draw do

  get "propart/index"

  resources :messages do
    member do
      get :reply
    end
  end

  match '/inbox' => 'messages#inbox', :as => 'inbox'
  match '/outbox' => 'messages#outbox', :as => 'outbox'
  match '/trash' => 'messages#trash', :as => 'trash'
  match '/trash/restore' => 'messages#restore', :as => 'restore'
  match '/messages/:id/reply' => 'messages#reply'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users

  resources :activities

  resources :attachments
  
  resources :discusses do
    resources :comments
  end

  resources :events do
    resources :comments
    member do
      get :asc
    end
  end
  
  resources :docs do
    resources :comments
  end

  resources :projects do
    member do
      get :join,:quit
    end
  end

  match '/myprojects' => 'myprojects#index', :as => 'myproject'

  match '/mydocs' => 'mydocs#index', :as => 'mydoc'

  match '/myevents' => 'myevents#index', :as =>'myevent'

  match '/tasks' => 'task#index', :as => 'task'

  match '/joins' => 'propart#index', :as => 'joins'

  root :to => 'projects#index'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  mount_uploader :attachment, AttachmentUploader

  attr_accessible :attachment, :description, :name
  validates_presence_of :attachment
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attachments }
    end
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/new
  # GET /attachments/new.json
  def new
    @attachment = Attachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/1/edit
  def edit
    @attachment = Attachment.find(params[:id])
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(params[:attachment])

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render json: @attachment, status: :created, location: @attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attachments/1
  # PUT /attachments/1.json
  def update
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(params[:attachment])
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to attachments_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= form_for @attachment,:html => {:class => 'form-hori'} do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> 
        prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class:'wysihtml5',:style => 'width:570px; height:100px;' %>
  </div>
  <div class="field">
    <%= f.label :attachment %>
    <div class="btn">
      <%= f.file_field :attachment %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing attachments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Attachment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attachments.each do |attachment| %>
  <tr>
    <td><%= attachment.name %></td>
    <td><%= attachment.description %></td>
    <td><%= attachment.attachment %></td>
    <td><%= link_to 'Show', attachment %></td>
    <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
    <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @attachment.name %>
</p>

<p>
  <b>Description:</b>
  <%= @attachment.description %>
</p>

<p>
  <b>Attachment:</b>  	  
  <%= link_to @attachment.attachment, @attachment.attachment.url %>
</p>


<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>