config/routes.rb
Writeriki::Application.routes.draw do

  get "propart/index"

  resources :messages do
    member do
      get :reply
    end
  end

  match '/inbox' => 'messages#inbox', :as => 'inbox'
  match '/outbox' => 'messages#outbox', :as => 'outbox'
  match '/trash' => 'messages#trash', :as => 'trash'
  match '/trash/restore' => 'messages#restore', :as => 'restore'
  match '/messages/:id/reply' => 'messages#reply'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users

  resources :activities

  resources :attachments
  
  resources :discusses do
    resources :comments
  end

  resources :events do
    resources :comments
    member do
      get :asc
    end
  end
  
  resources :docs do
    resources :comments
  end

  resources :projects do
    member do
      get :join,:quit
    end
  end

  match '/myprojects' => 'myprojects#index', :as => 'myproject'

  match '/mydocs' => 'mydocs#index', :as => 'mydoc'

  match '/myevents' => 'myevents#index', :as =>'myevent'

  match '/tasks' => 'task#index', :as => 'task'

  match '/joins' => 'propart#index', :as => 'joins'

  root :to => 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  attr_accessible :description, :end_at, :name, :start_at
  has_many :users, :through => :duties
  has_many :duties, :dependent => :delete_all

  has_many :docs
  has_many :events
  has_many :discusses
  has_many :files
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @joinings = Duty.all
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  def join
    @user = current_user
    @project = Project.find(params[:id])
    Duty.create!(:project_id => @project.id, :user_id => @user.id)

    respond_to do |format|
      format.html { redirect_to projects_url }
    end

  end

  def quit
    @user = current_user
    @project = Project.find(params[:id])
    Duty.find_by_project_id_and_user_id(@project.id,current_user.id).destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
    end

  end

  # POST /projects
  # POST /projects.json
  def create
    @user = current_user
    @project = Project.new(params[:project])
    @project.user_id = @user.id
    #@project.duties.build( :project_id => @project.id, :user_id => @user.id )

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label '项目名称', class:"control-label" %>
      <div class="controls">
        <%= f.text_field :name, class:'span4' %>
      </div>
  </div>

  <div class="control-group">
    <%= f.label '起始时间', class:"control-label" %>
      <div class="controls">
        <%= f.text_field :start_at, 'data-behaviour' => 'datepicker', class:"span4" %>
      </div>
  </div>

  <div class="control-group">
      <%= f.label '结束时间', class:"control-label" %>
        <div class="controls">
          <%= f.text_field :end_at, 'data-behaviour' => 'datepicker', class:"span4" %>
        </div>
  </div>

  <div class="control-group">
    <%= f.label '项目描述',class:'control-label' %>
    <div class="controls">
      <%= f.text_area :description, class:'wysihtml5',:style => 'width:570px; height:200px;' %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit '创建项目', class:'btn btn-danger' %>
    </div>
  </div>
<% end %>

<!--时间选择-->
<script type="text/javascript">
    $(document).on("focus", "[data-behaviour~='datepicker']", function(e){
        $(this).datepicker({"format": "yyyy-mm-dd", "weekStart": 1, "autoclose": true})
    });
</script>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% provide(:title, '所有项目') %>

<!-- title for the page -->
<h4 class="title-border-left">
  所有项目
</h4>

<!--排序方法-->
<div class="btn-group pull-right" style="margin-top: -39px;">
  <button class="btn">时间排序</button>
  <button class="btn dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li class="divider"></li>
    <li class="nav-header">按照起始时间</li>
    <li class="divider"></li>
    <li>
      <a href="">升序</a>
    </li>
    <li>
      <a href="">降序</a>
    </li>
    <li class="divider"></li>
    <li class="nav-header">按照结束时间</li>
    <li>
      <a href="">升序</a>
    </li>
    <li>
      <a href="">降序</a>
    </li>
    <li class="divider"></li>
  </ul>
</div>

<form class="input-append pull-right" style="margin-top: -39px;margin-right: 120px;">
  <input type="text" class="input-large search-query" placeholder="项目名称，发起人">
  <button type="submit" class="btn">Search</button>
</form>

<hr>

<table class="table table-bordered">
  <tr>
    <th class="t-center span1">预览</th>
    <th class="t-center span5">名称</th>
    <th class="t-center span2">起始时间</th>
    <th class="t-center span2">结束时间</th>
    <th class="t-center span1">发起人</th>
    <th class="t-center span1">成员</th>
  </tr>

  <% member = Array.new %>

  <!--当前用户创建的项目-->
  <% @projects.each do |project| %>
        <tr>
            <td class="t-center">
                <a href="#preview" class="btn btn-info btn-block" data-toggle="modal">
                    <i class="icon icon-white icon-eye-open"></i>
                </a>
            </td>

            <!--项目情况预览-->
            <div id="preview" class='modal hide fade'>
              <div class="modal-header">
                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                 <h4 id="myModalLabel" class="modal-title">
                   <%= project.name %>
                 </h4>
              </div>
              <div class="modal-body">
                  <p>One fine body…</p>
              </div>
              <div class="modal-footer">
                  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                  <button class="btn btn-primary">Save changes</button>
              </div>
            </div>
            <!--END-->

            <td class="t-center"><%= link_to project.name, project %></td>
            <td class="t-center"><%= project.start_at.strftime("%Y-%m-%d") %></td>
            <td class="t-center"><%= project.end_at.strftime("%Y-%m-%d") %></td>
            <% @users.each do |u| %>
               <% if project.user_id.to_s == u.id.to_s %>
                  <td class="t-center">
                      <a href="" data-placement="right">
                         <%= image_tag u.avatar.url(:thumb), class:"table-avatar" %>
                      </a>
                  </td>
               <% end %>
            <% end %>

            <!--展示项目成员头像-->
            <td class="t-center">
                <a href="#" id=<%= project.id.to_s %> class="btn btn-block btn-info" data-placement='right' title="项目成员列表" data-toggle="popover">
                  <!--加入这个项目的用户数量-->
                  <% @joins = Duty.where("project_id = ?", project.id) %>
                  <% if @joins.present? %>
                    <% @joins.each do |j| %>
                      <% member << j.user_id.to_s %>
                    <% end %>
                  <% end %>
                  <!--加上项目发起人本身-->
                    <%= member.length + 1 %>
                  <!--END-->
                </a>
            </td>
            <div id='mate_content' style="display:none;">
              <% @users.each do |u| %>
                <% member.each do |m| %>
                  <% if m.to_s == u.id.to_s %>
                    <%= image_tag u.avatar.url(:thumb), class:'table-avatar' %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
            <!--清空数组-->
              <% member.clear %>
            <!--END-->
        </tr>

<script type="text/javascript">
    $(document).ready(function(){
        $("<%= '#' + project.id.to_s %>").popover({
            html : true,
            content: function() {
                return $('#mate_content').html();
            }
        });
    });
</script>

  <% end %>
</table>

app/views/projects/new.html.erb
<% provide(:title, '创建新项目') %>

<h4 class="title-border-left">
  创建新项目
</h4>
<hr>

<%= render 'form' %>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>

<p>
  <b class="title-left">项目名称:&nbsp;&nbsp;</b>
  <%= @project.name %>
  <span class='pull-right'><%= @project.end_at.strftime("%Y-%m-%d") %></span>
  <b class="pull-right">结束时间:&nbsp;</b>
  <span class="pull-right" style="margin-right:10px;"><%= @project.start_at.strftime("%Y-%m-%d") %></span>
  <b class="pull-right">起始时间:&nbsp;</b>
</p>

<hr>

<div>
  <b class="title-left">项目描述:</b>
  <p class="title-tell"><%=raw @project.description %></p>
</div>

<hr>

<!-- 在此项目下的所有文档 -->
<div>
  <b class="title-left">所有文档：</b>
  <ol class="title-tell">
  <% @project.docs.each do |doc| %>
    <li><%= link_to doc.title, doc %></li>
  <% end %>
</ol>
</div>

<hr>

<!-- 在此项目下的所有事务 -->
<div>
  <b class="title-left">所有任务：</b>
  <ol class="title-tell">
  <% @project.events.each do |event| %>
    <li><%= link_to event.name, event %></li>
  <% end %>
</div>

<hr>

<!-- 在此项目下的所有讨论 -->
<div>
  <b class="title-left">所有讨论：</b>
  <ol class="title-tell">
  <% @project.discusses.each do |discuss| %>
    <li><%= link_to discuss.title, discuss %></li>
  <% end %>
</div>

<hr>

<!-- 在此项目下的所有文件资源 -->
<% if @project.user_id == current_user.id %>
    <%= link_to '编辑', edit_project_path(@project), class:'btn btn-info' %>
    <%= link_to '删除', project_path, :method => :delete, :data => { :confirm => 'Are you sure?' },class:'btn btn-danger' %>
<% elsif Duty.find_all_by_user_id_and_project_id(current_user.id,@project.id).present?  %>
    <%= link_to '退出项目', quit_project_path, :class => 'btn btn-danger' %>
<% else %>
    <%= link_to '加入项目', join_project_path, :class => 'btn btn-success' %>
<% end %>